export const statusTone: Record<string, string> = {
  Draft: "bg-muted text-muted-foreground border-border",
  Submitted: "bg-info/10 text-info border-info/20",
  "Under Review": "bg-warning/15 text-warning-foreground border-warning/30",
  Approved: "bg-success/15 text-success border-success/30",
  Processing: "bg-info/10 text-info border-info/20",
  "In Transit": "bg-primary/10 text-primary border-primary/20",
  Delivered: "bg-success/15 text-success border-success/30",
  Rejected: "bg-destructive/10 text-destructive border-destructive/25",
  Cancelled: "bg-muted text-muted-foreground border-border",
  Healthy: "bg-success/15 text-success border-success/30",
  "Low Stock": "bg-warning/15 text-warning-foreground border-warning/30",
  "Out of Stock": "bg-destructive/10 text-destructive border-destructive/25",
  Archived: "bg-muted text-muted-foreground border-border",
  "Return Pending": "bg-warning/15 text-warning-foreground border-warning/30",
  "Converted to Order": "bg-success/15 text-success border-success/30",
  "Partially Approved": "bg-warning/15 text-warning-foreground border-warning/30",
  Closed: "bg-muted text-muted-foreground border-border",
  High: "bg-destructive/10 text-destructive border-destructive/25",
  Medium: "bg-warning/15 text-warning-foreground border-warning/30",
  Low: "bg-muted text-muted-foreground border-border",
  ACTIVE: "bg-success/15 text-success border-success/30",
  INACTIVE: "bg-muted text-muted-foreground border-border",
  SUSPENDED: "bg-destructive/10 text-destructive border-destructive/25",
};
