/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StockRequestsIndexRouteImport } from './routes/stock-requests.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as ApprovalsIndexRouteImport } from './routes/approvals.index'
import { Route as StockRequestsNewRouteImport } from './routes/stock-requests.new'
import { Route as OrdersNewRouteImport } from './routes/orders.new'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as InventorySkuRouteImport } from './routes/inventory.$sku'
import { Route as ApprovalsIdRouteImport } from './routes/approvals.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRequestsIndexRoute = StockRequestsIndexRouteImport.update({
  id: '/stock-requests/',
  path: '/stock-requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsIndexRoute = ApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRequestsNewRoute = StockRequestsNewRouteImport.update({
  id: '/stock-requests/new',
  path: '/stock-requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InventorySkuRoute = InventorySkuRouteImport.update({
  id: '/inventory/$sku',
  path: '/inventory/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsIdRoute = ApprovalsIdRouteImport.update({
  id: '/approvals/$id',
  path: '/approvals/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals/$id': typeof ApprovalsIdRoute
  '/inventory/$sku': typeof InventorySkuRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/stock-requests/new': typeof StockRequestsNewRoute
  '/approvals/': typeof ApprovalsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/stock-requests/': typeof StockRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals/$id': typeof ApprovalsIdRoute
  '/inventory/$sku': typeof InventorySkuRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/stock-requests/new': typeof StockRequestsNewRoute
  '/approvals': typeof ApprovalsIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/stock-requests': typeof StockRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals/$id': typeof ApprovalsIdRoute
  '/inventory/$sku': typeof InventorySkuRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/stock-requests/new': typeof StockRequestsNewRoute
  '/approvals/': typeof ApprovalsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/stock-requests/': typeof StockRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals/$id'
    | '/inventory/$sku'
    | '/orders/$id'
    | '/orders/new'
    | '/stock-requests/new'
    | '/approvals/'
    | '/inventory/'
    | '/orders/'
    | '/stock-requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals/$id'
    | '/inventory/$sku'
    | '/orders/$id'
    | '/orders/new'
    | '/stock-requests/new'
    | '/approvals'
    | '/inventory'
    | '/orders'
    | '/stock-requests'
  id:
    | '__root__'
    | '/'
    | '/approvals/$id'
    | '/inventory/$sku'
    | '/orders/$id'
    | '/orders/new'
    | '/stock-requests/new'
    | '/approvals/'
    | '/inventory/'
    | '/orders/'
    | '/stock-requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsIdRoute: typeof ApprovalsIdRoute
  InventorySkuRoute: typeof InventorySkuRoute
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersNewRoute: typeof OrdersNewRoute
  StockRequestsNewRoute: typeof StockRequestsNewRoute
  ApprovalsIndexRoute: typeof ApprovalsIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  StockRequestsIndexRoute: typeof StockRequestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-requests/': {
      id: '/stock-requests/'
      path: '/stock-requests'
      fullPath: '/stock-requests/'
      preLoaderRoute: typeof StockRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals/': {
      id: '/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof ApprovalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-requests/new': {
      id: '/stock-requests/new'
      path: '/stock-requests/new'
      fullPath: '/stock-requests/new'
      preLoaderRoute: typeof StockRequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$sku': {
      id: '/inventory/$sku'
      path: '/inventory/$sku'
      fullPath: '/inventory/$sku'
      preLoaderRoute: typeof InventorySkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals/$id': {
      id: '/approvals/$id'
      path: '/approvals/$id'
      fullPath: '/approvals/$id'
      preLoaderRoute: typeof ApprovalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsIdRoute: ApprovalsIdRoute,
  InventorySkuRoute: InventorySkuRoute,
  OrdersIdRoute: OrdersIdRoute,
  OrdersNewRoute: OrdersNewRoute,
  StockRequestsNewRoute: StockRequestsNewRoute,
  ApprovalsIndexRoute: ApprovalsIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  StockRequestsIndexRoute: StockRequestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
